/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as MangaIndexRouteImport } from './routes/manga.index'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ReadChapterIdRouteImport } from './routes/read.$chapterId'
import { Route as ApiPublicMdSplatRouteImport } from './routes/api/public/md.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIndexRoute = MangaIndexRouteImport.update({
  id: '/manga/',
  path: '/manga/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadChapterIdRoute = ReadChapterIdRouteImport.update({
  id: '/read/$chapterId',
  path: '/read/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMdSplatRoute = ApiPublicMdSplatRouteImport.update({
  id: '/api/public/md/$',
  path: '/api/public/md/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/anime/': typeof AnimeIndexRoute
  '/watch': typeof WatchRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$chapterId': typeof ReadChapterIdRoute
  '/manga/': typeof MangaIndexRoute
  '/api/public/md/$': typeof ApiPublicMdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/anime': typeof AnimeIndexRoute
  '/watch': typeof WatchRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$chapterId': typeof ReadChapterIdRoute
  '/manga': typeof MangaIndexRoute
  '/api/public/md/$': typeof ApiPublicMdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/owner': typeof OwnerRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$chapterId': typeof ReadChapterIdRoute
  '/manga/': typeof MangaIndexRoute
  '/api/public/md/$': typeof ApiPublicMdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/owner'
    | '/settings'
    | '/sources'
    | '/anime/'
    | '/watch'
    | '/manga/$id'
    | '/read/$chapterId'
    | '/manga/'
    | '/api/public/md/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/owner'
    | '/settings'
    | '/sources'
    | '/anime'
    | '/watch'
    | '/manga/$id'
    | '/read/$chapterId'
    | '/manga'
    | '/api/public/md/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/library'
    | '/owner'
    | '/settings'
    | '/sources'
    | '/manga/$id'
    | '/read/$chapterId'
    | '/manga/'
    | '/api/public/md/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  OwnerRoute: typeof OwnerRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  WatchRoute: typeof WatchRoute
  MangaIdRoute: typeof MangaIdRoute
  ReadChapterIdRoute: typeof ReadChapterIdRoute
  MangaIndexRoute: typeof MangaIndexRoute
  ApiPublicMdSplatRoute: typeof ApiPublicMdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/': {
      id: '/manga/'
      path: '/manga'
      fullPath: '/manga/'
      preLoaderRoute: typeof MangaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$chapterId': {
      id: '/read/$chapterId'
      path: '/read/$chapterId'
      fullPath: '/read/$chapterId'
      preLoaderRoute: typeof ReadChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/md/$': {
      id: '/api/public/md/$'
      path: '/api/public/md/$'
      fullPath: '/api/public/md/$'
      preLoaderRoute: typeof ApiPublicMdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  OwnerRoute: OwnerRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  WatchRoute: WatchRoute,
  MangaIdRoute: MangaIdRoute,
  ReadChapterIdRoute: ReadChapterIdRoute,
  MangaIndexRoute: MangaIndexRoute,
  ApiPublicMdSplatRoute: ApiPublicMdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
